

const ALL_PERMISSIONS = [
  "USER_CREATE",
  "USER_VIEW",
  "USER_UPDATE",
  "USER_DELETE",
  "ORG_CREATE",
  "ORG_VIEW",
  "ORG_UPDATE",
  "ORG_DELETE",
  "ROLE_CREATE",
  "ROLE_VIEW",
  "ROLE_UPDATE",
  "ROLE_DELETE",
  "DEPARTMENT_CREATE",
  "DEPARTMENT_VIEW",
  "DEPARTMENT_UPDATE",
  "DEPARTMENT_DELETE",
  "SITE_CREATE",
  "SITE_VIEW",
  "SITE_UPDATE",
  "SITE_DELETE",
  "DASHBOARD_VIEW",
  "DASHBOARD_ANALYTICS_VIEW",
  "ACTIVITY_VIEW"
];


export default ALL_PERMISSIONS;
